const GOOGLE_API_KEY = `test`

export const YOUTUBE_VIDEO_API = `https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&regionCode=US&key=${GOOGLE_API_KEY}`

export const DATA_FROM_YOUTUBE = {
  kind: "youtube#videoListResponse",
  etag: "XZnNITlnEhhAGHkTlfrKK5WyOzA",
  items: [
    {
      kind: "youtube#video",
      etag: "963NAXbcEEOkZE9n1fEwe8CBflk",
      id: "bNKXxwOQYB8",
      snippet: {
        publishedAt: "2024-02-19T08:58:08Z",
        channelId: "UC3IZKseVpdzPSBaWxBxundA",
        title: "LE SSERAFIM (르세라핌) 'EASY' OFFICIAL MV",
        description:
          "Creative Director : NU KIM\n\nVisual Creative Coordinating : Yujoo Kim\nStyle Directing : Yoon Cho, Soo Lee\nBrand Experience Design : Yoovin Baek, Hyemin Yoo\nContent Production : Yurok Jang, Jisoo Min\n\nA&R : Kyuyoung Kim, Yujeong Kim, Soyoon Park, Jennie Lee, Myeongji Kim\n\nPerformance Directing : Soyeon Park\nAssistant Directing : Soyoung Yoon, Yejin Lee\n\nMusic Video Director : Nina McNeely \nProducer : Collin Druz\nProduction Company : UnderWonder Content \nExecutive Producer : Frank Borin, Ivanna Borin \nDOP : Nikita Kuzmenko \nProduction Designer : Nucalifornia / Hugh Zeigler + Daniel Lane\n\nEditor : Taylor Tracy Walsh @ Cabin Editing Company \nColorist : Matt Osborne @ Company3 \nVFX : The Frender \nVFX Supervisor : Max Colt \nAdditional VFX : Roma VFX \n\n1st AD : Jonas Morales \n2nd AD : Damon Limbrick \nDirector Assistant : Jamie Donovan \nProduction Manager : Gabe Figueroa \nProduction Coordinator : Eliza Padden \n\nGaffer : Scott Moody \nKey Grip : Matt King, Charles Lenz \n1st AC : Nico Martin \n2nd AC : Carrie Lazar\n\n2D @ Emotion Creative \n2D Composite Artist : Moonyoung Go\n\nSOURCE MUSIC. Rights are reserved selectively in the video.\nUnauthorized reproduction is a violation of applicable laws.\nManufactured by SOURCE MUSIC, Seoul, Korea\n\nConnect with LE SSERAFIM:\nOFFICIAL YOUTUBE https://www.youtube.com/channel/UCs-QBT4qkj_YiQw1ZntDO3g  \nOFFICIAL INSTAGRAM https://www.instagram.com/le_sserafim/\nOFFICIAL TWITTER https://twitter.com/le_sserafim\nOFFICIAL JAPAN TWITTER https://twitter.com/le_sserafim_jp\nOFFICIAL FACEBOOK https://www.facebook.com/official.lesserafim/\nOFFICIAL WEVERSE https://weverse.onelink.me/qt3S/t2ra8uwj\nOFFICIAL TIKTOK https://www.tiktok.com/@le_sserafim\nOFFICIAL WEIBO https://weibo.com/LESSERAFIM\nOFFICIAL BILIBILI https://space.bilibili.com/627577002 \nOFFICIAL DOUYIN https://v.douyin.com/iJgLJpUp/\nOFFICIAL SOUNDCLOUD https://soundcloud.com/le_sserafim_official\n\n#LE_SSERAFIM #르세라핌 #LE_SSERAFIM_EASY #MakeItLookEasy",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "HYBE LABELS",
        tags: ["HYBE", "HYBE LABELS", "하이브", "하이브레이블즈"],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "LE SSERAFIM (르세라핌) 'EASY' OFFICIAL MV",
          description:
            "Creative Director : NU KIM\n\nVisual Creative Coordinating : Yujoo Kim\nStyle Directing : Yoon Cho, Soo Lee\nBrand Experience Design : Yoovin Baek, Hyemin Yoo\nContent Production : Yurok Jang, Jisoo Min\n\nA&R : Kyuyoung Kim, Yujeong Kim, Soyoon Park, Jennie Lee, Myeongji Kim\n\nPerformance Directing : Soyeon Park\nAssistant Directing : Soyoung Yoon, Yejin Lee\n\nMusic Video Director : Nina McNeely \nProducer : Collin Druz\nProduction Company : UnderWonder Content \nExecutive Producer : Frank Borin, Ivanna Borin \nDOP : Nikita Kuzmenko \nProduction Designer : Nucalifornia / Hugh Zeigler + Daniel Lane\n\nEditor : Taylor Tracy Walsh @ Cabin Editing Company \nColorist : Matt Osborne @ Company3 \nVFX : The Frender \nVFX Supervisor : Max Colt \nAdditional VFX : Roma VFX \n\n1st AD : Jonas Morales \n2nd AD : Damon Limbrick \nDirector Assistant : Jamie Donovan \nProduction Manager : Gabe Figueroa \nProduction Coordinator : Eliza Padden \n\nGaffer : Scott Moody \nKey Grip : Matt King, Charles Lenz \n1st AC : Nico Martin \n2nd AC : Carrie Lazar\n\n2D @ Emotion Creative \n2D Composite Artist : Moonyoung Go\n\nSOURCE MUSIC. Rights are reserved selectively in the video.\nUnauthorized reproduction is a violation of applicable laws.\nManufactured by SOURCE MUSIC, Seoul, Korea\n\nConnect with LE SSERAFIM:\nOFFICIAL YOUTUBE https://www.youtube.com/channel/UCs-QBT4qkj_YiQw1ZntDO3g  \nOFFICIAL INSTAGRAM https://www.instagram.com/le_sserafim/\nOFFICIAL TWITTER https://twitter.com/le_sserafim\nOFFICIAL JAPAN TWITTER https://twitter.com/le_sserafim_jp\nOFFICIAL FACEBOOK https://www.facebook.com/official.lesserafim/\nOFFICIAL WEVERSE https://weverse.onelink.me/qt3S/t2ra8uwj\nOFFICIAL TIKTOK https://www.tiktok.com/@le_sserafim\nOFFICIAL WEIBO https://weibo.com/LESSERAFIM\nOFFICIAL BILIBILI https://space.bilibili.com/627577002 \nOFFICIAL DOUYIN https://v.douyin.com/iJgLJpUp/\nOFFICIAL SOUNDCLOUD https://soundcloud.com/le_sserafim_official\n\n#LE_SSERAFIM #르세라핌 #LE_SSERAFIM_EASY #MakeItLookEasy",
        },
        defaultAudioLanguage: "ko",
      },
      contentDetails: {
        duration: "PT3M10S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "25610858",
        likeCount: "763264",
        favoriteCount: "0",
        commentCount: "26915",
      },
    },
    {
      kind: "youtube#video",
      etag: "3qVfXGLyEv6AprlG7nar7EwlRhQ",
      id: "-fGyurkia4s",
      snippet: {
        publishedAt: "2024-02-20T01:00:00Z",
        channelId: "UCvK5d4dVvVpez5s0eNpobMw",
        title: "Jamie Took a Pregnancy Test (Raw Reaction)!",
        description:
          "We found out some incredible news the other day, and we could not wait to tell YOU! But I wanted to make it special for you and all of our frans!  Many of you watched us get married, fall in love, renew our vows, suffer through pregnancy loss, have 2 incredible rainbow babies in Henley and Hendrix, and move into our forever home.  Your continued love and support means the world to us, especially because we are not shy about what we share with you.  All in an effort to help normalize stigmas, help shed light on difficult and taboo topics, and be of service to those who feel alone.  We feel extremely blessed, and are honored to share this next chapter of our lives with you.  We hope you will continue on this journey with us! 🩷🩷🙏🏻🙏🏻❤️❤️\n\n\n💬  Did you enjoy today's video? Tell us all about it in the comments below 📝\n\n✨  If you like this video, consider subscribing to Hanging with the Hehners using this Link! ⤵️\nhttps://www.youtube.com/c/jamieotisanddoughehner?sub_confirmation=1\n\n********************\n👋 Hello everyone and welcome to Hanging with the Hehners!\n\nI'm Jamie Otis Hehner and me and my hubby of 9.5 years, Doug Hehner met & married on the same day as strangers on season 1 of Lifetime TV's Married At First Sight.\n\nWe lost our first baby, Johnathan.👼🏼 While trying to grow our family, we lost a couple more babies. ➡️ Sooo, we feel exceptionally thankful for our two beautiful rainbow babies: Henley & Hendrix.\n\nNow we are embarking on a fun new adventure that hopefully helps us grow stronger as husband & wife, but also closer to our kiddos.\nWe are SO EXCITED for this wild, new experience & we can't wait to take YOU along the ride! \n➡️  So, on this channel, we share content on love, family, marriage, and lifestyle. We love to keep it real and fun (our subscribers can attest to this). We share our wins, losses, rock bottoms, and milestones with the aim of spreading love and positivity.👪✨\n\nWe're taking a risky step into the unknown, and we'd like to invite you to join us! ❤️\nSo, hit that “Subscribe” button and “ring” the bell to never miss a video. \n\n********************\n✅  Follow Hanging with the Hehners on Social Media:\n\nInstagram ▶️ http://instagram.com/jamienotis/\nTwitter ▶️ https://twitter.com/jamienotis\nFacebook ▶️ https://www.facebook.com/jamieNotis\n\n\n********************\n#FamilyVlog #pregnancyannouncement  #pregnancyjourney  #MarriedAtFirstSight",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/-fGyurkia4s/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/-fGyurkia4s/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/-fGyurkia4s/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/-fGyurkia4s/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/-fGyurkia4s/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Hanging with the Hehners",
        tags: [
          "Pregnancy",
          "preggo",
          "surprise",
          "ttc",
          "pregnant",
          "hehner",
          "announcement",
          "baby",
          "trying to conceive",
          "helpful tips",
          "mom life",
          "dad life",
          "family",
          "real talk",
          "doug",
          "jamie",
          "hanging",
          "vlog",
          "behind the scenes",
          "positivity",
          "mom",
          "dad",
          "fun",
          "funny",
          "reality tv",
          "married at first sight",
          "tv",
          "family life",
          "home",
          "chat",
          "feeling",
          "praying",
          "tips",
          "blessing",
          "helpful",
          "real life",
          "challenge",
          "hot",
          "intimate",
          "sex",
          "hope",
          "relationship",
          "married life",
          "parenting",
          "recovery",
          "motivational",
          "healing",
          "relate",
          "toddler talk",
          "advice",
          "from the heart",
          "best life",
          "love",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Jamie Took a Pregnancy Test (Raw Reaction)!",
          description:
            "We found out some incredible news the other day, and we could not wait to tell YOU! But I wanted to make it special for you and all of our frans!  Many of you watched us get married, fall in love, renew our vows, suffer through pregnancy loss, have 2 incredible rainbow babies in Henley and Hendrix, and move into our forever home.  Your continued love and support means the world to us, especially because we are not shy about what we share with you.  All in an effort to help normalize stigmas, help shed light on difficult and taboo topics, and be of service to those who feel alone.  We feel extremely blessed, and are honored to share this next chapter of our lives with you.  We hope you will continue on this journey with us! 🩷🩷🙏🏻🙏🏻❤️❤️\n\n\n💬  Did you enjoy today's video? Tell us all about it in the comments below 📝\n\n✨  If you like this video, consider subscribing to Hanging with the Hehners using this Link! ⤵️\nhttps://www.youtube.com/c/jamieotisanddoughehner?sub_confirmation=1\n\n********************\n👋 Hello everyone and welcome to Hanging with the Hehners!\n\nI'm Jamie Otis Hehner and me and my hubby of 9.5 years, Doug Hehner met & married on the same day as strangers on season 1 of Lifetime TV's Married At First Sight.\n\nWe lost our first baby, Johnathan.👼🏼 While trying to grow our family, we lost a couple more babies. ➡️ Sooo, we feel exceptionally thankful for our two beautiful rainbow babies: Henley & Hendrix.\n\nNow we are embarking on a fun new adventure that hopefully helps us grow stronger as husband & wife, but also closer to our kiddos.\nWe are SO EXCITED for this wild, new experience & we can't wait to take YOU along the ride! \n➡️  So, on this channel, we share content on love, family, marriage, and lifestyle. We love to keep it real and fun (our subscribers can attest to this). We share our wins, losses, rock bottoms, and milestones with the aim of spreading love and positivity.👪✨\n\nWe're taking a risky step into the unknown, and we'd like to invite you to join us! ❤️\nSo, hit that “Subscribe” button and “ring” the bell to never miss a video. \n\n********************\n✅  Follow Hanging with the Hehners on Social Media:\n\nInstagram ▶️ http://instagram.com/jamienotis/\nTwitter ▶️ https://twitter.com/jamienotis\nFacebook ▶️ https://www.facebook.com/jamieNotis\n\n\n********************\n#FamilyVlog #pregnancyannouncement  #pregnancyjourney  #MarriedAtFirstSight",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT4M27S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "160853",
        likeCount: "5962",
        favoriteCount: "0",
        commentCount: "750",
      },
    },
    {
      kind: "youtube#video",
      etag: "rUX3hfdKJ4JKsl9ZjgtX3ImM6yk",
      id: "8Ou7w3Sxk5E",
      snippet: {
        publishedAt: "2024-02-18T19:03:11Z",
        channelId: "UC7zsxKqd5MicTf4VhS9Y74g",
        title: "A YouTuber Made the Most Insane Animated Movie Ever",
        description:
          'You guys need to try air up! Get yours now and let me know what you think ►https://airup.link/3OQJ9yT \n\nI watched the movie "Our Drawings" made by a YouTuber. It ruined my life I think! Enjoy!\n\ngo watch the full movie it\'s a very fun watch: https://www.youtube.com/watch?v=G1LhdhQEKtg\n\nWATCH MY COMEDY SPECIAL\n ► https://www.patreon.com/veryreallygood/shop/keep-busy-kurtis-conner-comedy-special-107938?source=storefront\n\nFOLLOW ME:\n► https://instagram.com/kurtisconner/\n► https://twitter.com/kurtisconner\n\nMERCH \n► https://shop.kurtisconner.com/\n\nWATCH MY PODCAST:\n►  @veryreallygood  \n\nLISTEN TO MY PODCAST:\n► https://open.spotify.com/show/3nGVLHpNXo6MiHQmotIAHG?si=T9Q-NAIOQG6BpWL_7oUvDA\n► https://podcasts.apple.com/ca/podcast/very-really-good/id1335843384\n\nthumbnail by @dvdaltizer \n\nthanks for watching!\n\ncomment "r u from ohio or something?” if ur reading this\n\n#kurtisconner',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/8Ou7w3Sxk5E/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/8Ou7w3Sxk5E/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/8Ou7w3Sxk5E/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/8Ou7w3Sxk5E/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/8Ou7w3Sxk5E/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Kurtis Conner",
        tags: ["kurtis conner", "kurtis connor", "our drawings"],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "A YouTuber Made the Most Insane Animated Movie Ever",
          description:
            'You guys need to try air up! Get yours now and let me know what you think ►https://airup.link/3OQJ9yT \n\nI watched the movie "Our Drawings" made by a YouTuber. It ruined my life I think! Enjoy!\n\ngo watch the full movie it\'s a very fun watch: https://www.youtube.com/watch?v=G1LhdhQEKtg\n\nWATCH MY COMEDY SPECIAL\n ► https://www.patreon.com/veryreallygood/shop/keep-busy-kurtis-conner-comedy-special-107938?source=storefront\n\nFOLLOW ME:\n► https://instagram.com/kurtisconner/\n► https://twitter.com/kurtisconner\n\nMERCH \n► https://shop.kurtisconner.com/\n\nWATCH MY PODCAST:\n►  @veryreallygood  \n\nLISTEN TO MY PODCAST:\n► https://open.spotify.com/show/3nGVLHpNXo6MiHQmotIAHG?si=T9Q-NAIOQG6BpWL_7oUvDA\n► https://podcasts.apple.com/ca/podcast/very-really-good/id1335843384\n\nthumbnail by @dvdaltizer \n\nthanks for watching!\n\ncomment "r u from ohio or something?” if ur reading this\n\n#kurtisconner',
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT30M22S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1623279",
        likeCount: "131992",
        favoriteCount: "0",
        commentCount: "7429",
      },
    },
    {
      kind: "youtube#video",
      etag: "_tevDzoM5vUwuzeKft0rhKlm4yk",
      id: "zNgI7Lv2C1o",
      snippet: {
        publishedAt: "2024-02-19T16:21:01Z",
        channelId: "UCbPY1Efha9VPRBYW2x1M16A",
        title: "JJ Redick On Fixing This Awful NBA All-Star Game",
        description:
          "In this clip, JJ Redick talks about the 2024 NBA All Star Game and if there's a fix to make it more competitive. He talks about the lowlights like Luka Donic and his 3/4 court heave and the highlights like Tyrese Haliburton. \n\nSubscribe to The Old Man and The Three podcast w/ JJ Redick (ESPN / First Take) and Tommy Alter YouTube channel today for more NBA analysis, player interviews and highlights.\n\n#nba",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/zNgI7Lv2C1o/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/zNgI7Lv2C1o/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/zNgI7Lv2C1o/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/zNgI7Lv2C1o/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/zNgI7Lv2C1o/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "JJ Redick",
        tags: [
          "jj redick",
          "jj redick youtube",
          "jj redick podcast",
          "jj redick youtube channel",
          "the old man and the three",
          "nba",
          "jj redick espn",
          "espn",
          "first take",
          "nba highlights",
          "jj redick interview",
          "nba all star game",
          "all star game",
          "jj redick all star game",
          "all star game highlights",
          "2024 nba all star game",
          "tyrese haliburton",
          "tyrese haliburton highlights",
          "luka doncic",
          "luka doncic highlights",
          "jj redick luka doncic",
          "jj redick damian lillard",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        localized: {
          title: "JJ Redick On Fixing This Awful NBA All-Star Game",
          description:
            "In this clip, JJ Redick talks about the 2024 NBA All Star Game and if there's a fix to make it more competitive. He talks about the lowlights like Luka Donic and his 3/4 court heave and the highlights like Tyrese Haliburton. \n\nSubscribe to The Old Man and The Three podcast w/ JJ Redick (ESPN / First Take) and Tommy Alter YouTube channel today for more NBA analysis, player interviews and highlights.\n\n#nba",
        },
      },
      contentDetails: {
        duration: "PT7M26S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "472331",
        likeCount: "10211",
        favoriteCount: "0",
        commentCount: "3129",
      },
    },
    {
      kind: "youtube#video",
      etag: "7DT6W5ewmJ2G4R3M8ghH0YbowdA",
      id: "ImpteXpAAvc",
      snippet: {
        publishedAt: "2024-02-20T06:39:44Z",
        channelId: "UCt7fwAhXDy3oNFTAzF2o8Pw",
        title: "Yeat - 2093 ALBUM REVIEW",
        description:
          "Listen: https://www.youtube.com/watch?v=n28xgaiXy8g\n\nIt's wild how much ambition and eccentricity Yeat shows on 2093.\n\nMore rap reviews: https://www.youtube.com/playlist?list=PLP4CSgl7K7ormBIO138tYonB949PHnNcP\n\n===================================\nSubscribe: http://bit.ly/1pBqGCN\n\nPatreon: https://www.patreon.com/theneedledrop\n\nOfficial site: http://theneedledrop.com\n\nTwitter: http://twitter.com/theneedledrop\n\nInstagram: https://www.instagram.com/afantano\n\nTikTok: https://www.tiktok.com/@theneedletok\n\nTND Twitch: https://www.twitch.tv/theneedledrop\n\nTeam: Jeremy - Lead Edits / Anthony - Final Cuts / Austen - Proofing, Posting\n===================================\n\nFAV TRACKS: PSYCHO CEO, POWER TRIP, BREATHE, MORË, BOUGHT THE EARTH, U SHOULD KNOW, ILUV, TELL MË, SHADE, RIOT & SET IT OFF, MR. INBETWEENIT, PSYCHOCAINË, IF WE BEING REAL, 1093\n\nLEAST FAV TRACK: 2093\n\nYEAT - 2093 / 2024 / FIELD TRIP / DYSTOPIAN HIP HOP, EBM, RAGE\n\n8/10 https://www.theneedledrop.com/loved-list/2024\n\nY'all know this is just my opinion, right?",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/ImpteXpAAvc/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/ImpteXpAAvc/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/ImpteXpAAvc/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/ImpteXpAAvc/sddefault.jpg",
            width: 640,
            height: 480,
          },
        },
        channelTitle: "theneedledrop",
        tags: [
          "album",
          "review",
          "music",
          "reviews",
          "indie",
          "new",
          "lyrics",
          "listen",
          "track",
          "concert",
          "live",
          "update",
          "the needle drop",
          "anthony fantano",
          "vlog",
          "talk",
          "discussion",
          "music nerd",
          "song",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Yeat - 2093 ALBUM REVIEW",
          description:
            "Listen: https://www.youtube.com/watch?v=n28xgaiXy8g\n\nIt's wild how much ambition and eccentricity Yeat shows on 2093.\n\nMore rap reviews: https://www.youtube.com/playlist?list=PLP4CSgl7K7ormBIO138tYonB949PHnNcP\n\n===================================\nSubscribe: http://bit.ly/1pBqGCN\n\nPatreon: https://www.patreon.com/theneedledrop\n\nOfficial site: http://theneedledrop.com\n\nTwitter: http://twitter.com/theneedledrop\n\nInstagram: https://www.instagram.com/afantano\n\nTikTok: https://www.tiktok.com/@theneedletok\n\nTND Twitch: https://www.twitch.tv/theneedledrop\n\nTeam: Jeremy - Lead Edits / Anthony - Final Cuts / Austen - Proofing, Posting\n===================================\n\nFAV TRACKS: PSYCHO CEO, POWER TRIP, BREATHE, MORË, BOUGHT THE EARTH, U SHOULD KNOW, ILUV, TELL MË, SHADE, RIOT & SET IT OFF, MR. INBETWEENIT, PSYCHOCAINË, IF WE BEING REAL, 1093\n\nLEAST FAV TRACK: 2093\n\nYEAT - 2093 / 2024 / FIELD TRIP / DYSTOPIAN HIP HOP, EBM, RAGE\n\n8/10 https://www.theneedledrop.com/loved-list/2024\n\nY'all know this is just my opinion, right?",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT13M4S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "172070",
        likeCount: "12354",
        favoriteCount: "0",
        commentCount: "1380",
      },
    },
    {
      kind: "youtube#video",
      etag: "963NAXbcEEOkZE9n1fEwe8CBflk",
      id: "bNKXxwOQYB8",
      snippet: {
        publishedAt: "2024-02-19T08:58:08Z",
        channelId: "UC3IZKseVpdzPSBaWxBxundA",
        title: "LE SSERAFIM (르세라핌) 'EASY' OFFICIAL MV",
        description:
          "Creative Director : NU KIM\n\nVisual Creative Coordinating : Yujoo Kim\nStyle Directing : Yoon Cho, Soo Lee\nBrand Experience Design : Yoovin Baek, Hyemin Yoo\nContent Production : Yurok Jang, Jisoo Min\n\nA&R : Kyuyoung Kim, Yujeong Kim, Soyoon Park, Jennie Lee, Myeongji Kim\n\nPerformance Directing : Soyeon Park\nAssistant Directing : Soyoung Yoon, Yejin Lee\n\nMusic Video Director : Nina McNeely \nProducer : Collin Druz\nProduction Company : UnderWonder Content \nExecutive Producer : Frank Borin, Ivanna Borin \nDOP : Nikita Kuzmenko \nProduction Designer : Nucalifornia / Hugh Zeigler + Daniel Lane\n\nEditor : Taylor Tracy Walsh @ Cabin Editing Company \nColorist : Matt Osborne @ Company3 \nVFX : The Frender \nVFX Supervisor : Max Colt \nAdditional VFX : Roma VFX \n\n1st AD : Jonas Morales \n2nd AD : Damon Limbrick \nDirector Assistant : Jamie Donovan \nProduction Manager : Gabe Figueroa \nProduction Coordinator : Eliza Padden \n\nGaffer : Scott Moody \nKey Grip : Matt King, Charles Lenz \n1st AC : Nico Martin \n2nd AC : Carrie Lazar\n\n2D @ Emotion Creative \n2D Composite Artist : Moonyoung Go\n\nSOURCE MUSIC. Rights are reserved selectively in the video.\nUnauthorized reproduction is a violation of applicable laws.\nManufactured by SOURCE MUSIC, Seoul, Korea\n\nConnect with LE SSERAFIM:\nOFFICIAL YOUTUBE https://www.youtube.com/channel/UCs-QBT4qkj_YiQw1ZntDO3g  \nOFFICIAL INSTAGRAM https://www.instagram.com/le_sserafim/\nOFFICIAL TWITTER https://twitter.com/le_sserafim\nOFFICIAL JAPAN TWITTER https://twitter.com/le_sserafim_jp\nOFFICIAL FACEBOOK https://www.facebook.com/official.lesserafim/\nOFFICIAL WEVERSE https://weverse.onelink.me/qt3S/t2ra8uwj\nOFFICIAL TIKTOK https://www.tiktok.com/@le_sserafim\nOFFICIAL WEIBO https://weibo.com/LESSERAFIM\nOFFICIAL BILIBILI https://space.bilibili.com/627577002 \nOFFICIAL DOUYIN https://v.douyin.com/iJgLJpUp/\nOFFICIAL SOUNDCLOUD https://soundcloud.com/le_sserafim_official\n\n#LE_SSERAFIM #르세라핌 #LE_SSERAFIM_EASY #MakeItLookEasy",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/bNKXxwOQYB8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "HYBE LABELS",
        tags: ["HYBE", "HYBE LABELS", "하이브", "하이브레이블즈"],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "LE SSERAFIM (르세라핌) 'EASY' OFFICIAL MV",
          description:
            "Creative Director : NU KIM\n\nVisual Creative Coordinating : Yujoo Kim\nStyle Directing : Yoon Cho, Soo Lee\nBrand Experience Design : Yoovin Baek, Hyemin Yoo\nContent Production : Yurok Jang, Jisoo Min\n\nA&R : Kyuyoung Kim, Yujeong Kim, Soyoon Park, Jennie Lee, Myeongji Kim\n\nPerformance Directing : Soyeon Park\nAssistant Directing : Soyoung Yoon, Yejin Lee\n\nMusic Video Director : Nina McNeely \nProducer : Collin Druz\nProduction Company : UnderWonder Content \nExecutive Producer : Frank Borin, Ivanna Borin \nDOP : Nikita Kuzmenko \nProduction Designer : Nucalifornia / Hugh Zeigler + Daniel Lane\n\nEditor : Taylor Tracy Walsh @ Cabin Editing Company \nColorist : Matt Osborne @ Company3 \nVFX : The Frender \nVFX Supervisor : Max Colt \nAdditional VFX : Roma VFX \n\n1st AD : Jonas Morales \n2nd AD : Damon Limbrick \nDirector Assistant : Jamie Donovan \nProduction Manager : Gabe Figueroa \nProduction Coordinator : Eliza Padden \n\nGaffer : Scott Moody \nKey Grip : Matt King, Charles Lenz \n1st AC : Nico Martin \n2nd AC : Carrie Lazar\n\n2D @ Emotion Creative \n2D Composite Artist : Moonyoung Go\n\nSOURCE MUSIC. Rights are reserved selectively in the video.\nUnauthorized reproduction is a violation of applicable laws.\nManufactured by SOURCE MUSIC, Seoul, Korea\n\nConnect with LE SSERAFIM:\nOFFICIAL YOUTUBE https://www.youtube.com/channel/UCs-QBT4qkj_YiQw1ZntDO3g  \nOFFICIAL INSTAGRAM https://www.instagram.com/le_sserafim/\nOFFICIAL TWITTER https://twitter.com/le_sserafim\nOFFICIAL JAPAN TWITTER https://twitter.com/le_sserafim_jp\nOFFICIAL FACEBOOK https://www.facebook.com/official.lesserafim/\nOFFICIAL WEVERSE https://weverse.onelink.me/qt3S/t2ra8uwj\nOFFICIAL TIKTOK https://www.tiktok.com/@le_sserafim\nOFFICIAL WEIBO https://weibo.com/LESSERAFIM\nOFFICIAL BILIBILI https://space.bilibili.com/627577002 \nOFFICIAL DOUYIN https://v.douyin.com/iJgLJpUp/\nOFFICIAL SOUNDCLOUD https://soundcloud.com/le_sserafim_official\n\n#LE_SSERAFIM #르세라핌 #LE_SSERAFIM_EASY #MakeItLookEasy",
        },
        defaultAudioLanguage: "ko",
      },
      contentDetails: {
        duration: "PT3M10S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "25610858",
        likeCount: "763264",
        favoriteCount: "0",
        commentCount: "26915",
      },
    },
  ],
  nextPageToken: "CAUQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 5,
  },
}
